server:
  port: 8080
spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:6541/prescriptions-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: iamroot
