CREATE TABLE IF NOT EXISTS "prescriptions_collection"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "collection" TEXT NOT NULL,
    CONSTRAINT pk_collection PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "icd_codes"
(
    "id"            VARCHAR,
    "collection_id" BIGINT NOT NULL,
    CONSTRAINT pk_icd_code PRIMARY KEY ("id"),
    CONSTRAINT fk_collection_id FOREIGN KEY ("collection_id") REFERENCES "prescriptions_collection" ("id") ON UPDATE CASCADE
);